<a href="https://colab.research.google.com/github/vihaankrishna100/AI-Neural-Networks/blob/main/MoviePanda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/movies_metadata.csv').dropna(axis=1, how='all')
df.head()

,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862.0,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844.0,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602.0,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.712900,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357.0,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862.0,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df.shape

(45453, 23)

In [ ]:
df.columns

Index(['belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
budget_df = df[df[('budget')] > 1000000]
budget_df.shape

(7208, 23)

In [ ]:
budget_lookup = budget_df.budget
budget_lookup.index = budget_df.title
budget_lookup['Dead Presidents']

10000000

In [ ]:
budget_df = budget_df.sort_values('title')
budget_lookup_as_and_bs = budget_df[budget_df["title"].str[0].isin(['A', 'B'])]
count = budget_lookup_as_and_bs.shape[0]
print(count)

933

In [ ]:

time_scheduler = df.set_index('runtime')
time_scheduler = time_scheduler[['title', 'release_date']]
time_scheduler.loc[154]

                                                     title release_date
runtime
154.0                                         Pulp Fiction   1994-09-10
154.0                                             The Firm   1993-06-30
154.0                                     The Ruling Class   1972-09-13
154.0                                         Jackie Brown   1997-12-24
154.0                                     The Color Purple   1985-12-18
154.0                                        Amores perros   2000-06-16
154.0                               Va Savoir (Who Knows?)   2001-09-28
154.0                                     The Last Samurai   2003-12-05
154.0                                        Cold Mountain   2003-12-24
154.0                                   Sodom and Gomorrah   1962-01-01
154.0                                             Lord Jim   1965-02-15
154.0                           1492: Conquest of Paradise   1992-10-09
154.0                                               Wilson   1944-08-01
154.0                                    55 Days at Peking   1963-05-06
154.0                                     Superman Returns   2006-06-28
154.0                                               Krrish   2006-06-23
154.0                                      Cheyenne Autumn   1964-10-03
154.0                                     The Love of Siam   2007-11-22
154.0                                     Twenty-Four Eyes   1954-09-15
154.0                       Transformers: Dark of the Moon   2011-06-28
154.0                                          Sweet Bunch   1983-10-19
154.0                                    Little White Lies   2010-10-20
154.0                                Yamla Pagla Deewana 2   2013-06-07
154.0    The Adventures of Sherlock Holmes and Dr. Wats...   1981-01-02
154.0                                        Beloved Enemy   1979-05-22
154.0                                            Magicians   1982-01-01
154.0                                               Zameen   2003-09-26
154.0                                               Singam   2010-05-28
154.0                                     Sanam Teri Kasam   2016-02-05
154.0                         Christmas Time In South Park   2000-10-09
154.0                                            The Tuner   2004-09-06

In [ ]:
x=df.sort_values(by='runtime', ascending=False)
x.iloc[154]

belongs_to_collection                                                  NaN
budget                                                                   0
genres                   [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...
homepage                                                               NaN
id                                                                  5998.0
imdb_id                                                          tt0013086
original_language                                                       de
original_title                                     Dr. Mabuse, der Spieler
overview                 Arch-criminal Dr. Mabuse, who is a master of d...
popularity                                                        3.275117
poster_path                               /9pK6ygSwdLdlx12PgUqLGiMFfnt.jpg
production_companies               [{'name': 'Uco-Film GmbH', 'id': 2127}]
production_countries             [{'iso_3166_1': 'DE', 'name': 'Germany'}]
release_date                                                    1922-04-27
revenue                                                                0.0
runtime                                                              270.0
spoken_languages                                                        []
status                                                            Released
tagline                                                                NaN
title                                              Dr. Mabuse, the Gambler
video                                                                False
vote_average                                                           7.6
vote_count                                                            35.0
Name: 4638, dtype: object

In [ ]:
df_highly_voted = df[df.vote_count > 20]
df_high_rated = df_highly_voted[df_highly_voted.vote_average > 8]
df_high_rated[['title', 'vote_average', 'vote_count']]

                               title  vote_average  vote_count
46                             Se7en           8.1      5915.0
49                The Usual Suspects           8.1      3334.0
109                      Taxi Driver           8.1      2632.0
256                        Star Wars           8.1      6778.0
289           Leon: The Professional           8.2      4293.0
...                              ...           ...         ...
43576    Pink Floyd: Live at Pompeii           8.3        35.0
43962                    Life Cycles           8.8        27.0
44377  Hasan Minhaj: Homecoming King           8.1        22.0
44664  Black Mirror: White Christmas           8.3       211.0
45424                 In a Heartbeat           8.3       146.0

[178 rows x 3 columns]

In [ ]:
my_votes = {
    "Star Wars": 9,
    "Paris is Burning": 8,
    "Dead Poets Society": 7,
    "The Empire Strikes Back": 9.5,
    "The Shining": 8,
    "Return of the Jedi": 8,
    "1941": 8,
    "Forrest Gump": 7.5,
}

my_ratings = pd.Series(my_votes).rename("my_votes")
z = df_high_rated.set_index('title')
z = z.join(my_ratings).dropna(axis = 0)
z['percent_difference'] = 100 * ([z["vote_average"]- cv["my_votes"]]) / z["my_votes"]

In [ ]:
df['revenue'].max()

2787965087.0

In [ ]:
movie_100 = df.sort_values(by='popularity', ascending=False)
movie_100.iloc[100]

belongs_to_collection    {'id': 295, 'name': 'Pirates of the Caribbean ...
budget                                                           300000000
genres                   [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
homepage                      http://disney.go.com/disneypictures/pirates/
id                                                                   285.0
imdb_id                                                          tt0449088
original_language                                                       en
original_title                    Pirates of the Caribbean: At World's End
overview                 Captain Barbossa, long believed to be dead, ha...
popularity                                                       31.363664
poster_path                               /bXb00CkHqx7TPchTGG131sWV59y.jpg
production_companies     [{'name': 'Walt Disney Pictures', 'id': 2}, {'...
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    2007-05-19
revenue                                                        961000000.0
runtime                                                              169.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                     At the end of the world, the adventure begins.
title                             Pirates of the Caribbean: At World's End
video                                                                False
vote_average                                                           6.9
vote_count                                                          4627.0
Name: 11827, dtype: object

In [ ]:
df['runtime'].mean()

94.13477750979133